name: build
on: [push, pull_request]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C test test test++ elk EXTRA="-lm"
  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C test test++ elk upload-coverage
  Windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: vc2017
      run: make -C test vc2017
    - name: mingw
      run: make -C test mingw
  ArduinoUno:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: uno
      run: make -C test uno
